name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      - uses: aquiladev/ipfs-action@v0.1.5
        id: ipfs-add
        with:
          path: ./public
          service: infura
      - name: Update DNSLink
        run: npx dnslink-cloudflare -d gamey.tech -l /ipfs/QmPhFNTG9YJQ79SHKZXGdZeKEZNzv62vNQM4GdDfq3kHxd -r _dnslink
        env:
          CF_API_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
